name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn run build

      # - name: Run Tests
      #   run: |
      #     yarn run test

      - name: Lint
        run: |
          yarn run lint

      - name: Type Check
        run: |
          yarn run typecheck

      - name: Audit dependencies & fail on high or critical vulnerabilities
        run: |
          yarn audit --severity=high

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
