name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn run build

      # - name: Run Tests
      #   run: |
      #     yarn run test

      - name: Lint
        run: |
          yarn run lint

      - name: Type Check
        run: |
          yarn run typecheck

      - name: Audit dependencies & fail on high or critical vulnerabilities
        run: |
          audit_output=$(yarn audit --json)
          high_vulnerabilities=$(echo "$audit_output" | jq '.data.vulnerabilities | map(select(.severity == "high"))')
          if [ $(echo "$high_vulnerabilities" | jq length) -gt 0 ]; then
            echo "High vulnerabilities found:"
            echo "$high_vulnerabilities"
            exit 1
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
