name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn run build

      # - name: Run Tests
      #   run: |
      #     yarn run test

      - name: Lint
        run: |
          yarn run lint

      - name: Type Check
        run: |
          yarn run typecheck

      - name: Check for vulnerabilities
        run: yarn audit --json
        id: audit
      - name: Fail on high or critical vulnerabilities
        run: |
          severity=$(jq -r '.data.vulnerabilities | max_by(.severity) | .severity' ${{ steps.audit.outputs.stdout }})
          if [[ "$severity" == "high" || "$severity" == "critical" ]]; then
            echo "Vulnerabilities found with severity: $severity"
            exit 1
          fi


      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
